baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

[languages]
  [languages.en]
    title = "Cyber Security Portfolio"
    keywords = ""
    copyright = ""
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read Other Posts"

    [languages.en.params.logo]
      logoText = "Cyber Security Portfolio :: Blog Posts"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "aboutme"
        name = "About Me"
        url = "/about-me"
      [[languages.en.menu.main]]
        identifier = "slo"
        name = "Subject Learning Objectives (SLO)"
        url = "/subject-learning-objectives"
	[[languages.en.menu.main]]
        identifier = "final"
        name = "Conclusion / Final Reflection"
        url = "/final_portfolio"
